---
title: "Summary"
author:
- Sandeep Srikonda
- Banish Ojha
- Swetha Pydi
- Alisha Pradhan

date: "`r Sys.Date()`"
---

Remember to write your thoughts as a book report.
I expect the same _content_ as your presentation, but the working should reflect the new medium.

# Read and Review

Individually read and review the paper.
As a group, please summarize your thoughts including the following:

1. How original is the topic?

    Ans: The topic is not very original since NN and Logistic regression are popular, but the study does a good job of pulling in information from various other literature.

2. What is the main question addressed by the research?

    Ans: The objective of the research is to find the current evidence from various project research directly comparing logistical regression versus neural network classification approaches in healthcare.

3. Are the conclusions consistent with the evidence and arguments presented?

    Ans: Yes, the conclusions are consistent with evidence and arguments presented. On most of the cases examined across the range of clinical settings, simple LR model demonstrate reasonable performance which is only marginally improved when using NN method. 60% of cases, the overall improvement in performance of NNs as compared to LR was moderately small (mean improvement in AUC of 0.03).

# A.I Help

Pretend that ChatGPT (or similar tool) is a new team member.
Ask ChatGPT to contribute to the group project.
Keep diligent notes as to your conversation.
Science is about reproducibility, if your classmates can not repeat the process using your steps, you will be marked down in the next assignment.

### Prerequisites:

1. If you’re running the ipython notebook locally, Installation of requirements.txt for all required packages [preferably on separate environment] 

2. OpenAI API key creation [Creating account in https://platform.openai.com/, navigating to user -> Api-Keys: https://platform.openai.com/account/api-keys and create or copy as necessary] 

3. Create Pinecone API key [Ref: https://docs.pinecone.io/docs/quickstart ]

### Steps:

1. We suggest using google colab environment to run the ipython notebook file provided to you. 

2. Follow the instruction provided in prerequisites section to setup the API keys 

3. Create a text file called “api_keys.txt” containing the information about the api keys and environment. Format:  

4. Each entry Per line: 

  1. OpenAPI key 

  2. Pinecone access key 

  3. Pinecone Environment 

5. Open the provided ipynb file in google colab 

6. Upload the research-paper-text.txt document to your colab runtime environment. You can upload the file using the file browser menu on the left hand side 

7. Run each cell in succession to setup the packages and to get the system ready to answer queries about the paper. 

8. Once you reach the Q and A section of the file, run the query for each section and observe the output displayed after the cell

# Compare and contrast

Compare and contrast what you, as a human team member, _understood_ to what ChatGPT, as an A.I. team member, _understood_.

1. Did ChatGPT help fill in your understanding of the paper?
2. Did ChatGPT miss the mark in a meaningful way?